### ISSUE TITLE
Using the protocol builder

### ISSUE THREAD

**Issue by RadYio** [viclew1/DofusProtocolUpdater#2]
You wrote a great wiki, but I still don't understand what I have to do to export a protocol from the swf file using your tools.

Could you add me on Discord, please? I would appreciate it if you could provide some examples or clarification regarding your project. Discord: RadYio#1590

BTW: May you have to merge the main and master branch, to keep the new changes on the master.

**Comment by viclew1** [comment]
Hey, this repo is more or less discontinued and is now included in the VLDofusBot repository.
You can join the bot's discord for any help though : https://discord.gg/v45AA3dtYz

And forgot there is even a main branch, deleted it thanks !
